# This workflow tests github action feature and integration

name: ActionTest

on:
  push:
    branches: [ main ]

jobs:

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  ActionTest:

    runs-on: ubuntu-latest

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: CredSweeper test
      # TODO: change @action to release point with the action
      uses: Samsung/CredSweeper@f9ec85a72a3295ecadb5e5df0e689135a9bb4a0d # main
      with:
        # args - arguments to credsweeper tool. See default values in action.yml
        args: --path ./tests/samples/ --save-json

    - name: Prepare commit status
      run: |
        ITEMS_CNT=$(jq '. | length' output.json)
        if [ 1 -lt ${ITEMS_CNT} ]; then
            echo "Samples were successfully scanned"
        else
            echo "Unexpected items: ${ITEMS_CNT}"
            exit 1
        fi

    - name: CredSweeper report
      if: always()
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: output.json
        path: output.json

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
