# This workflow checks whether last release is not too old

name: Check last release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '59 23 * * 0'

permissions:
  contents: read

jobs:

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  rottenness:

    runs-on: ubuntu-latest

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: Check last release date
      continue-on-error: true
      run: |
        latest_release="$(curl --silent https://api.github.com/repos/Samsung/CredSweeper/releases/latest)"
        published_date=$(echo "${latest_release}" | jq --raw-output '.published_at')
        release_age=$(( $(date +%s) - $(date --date="${published_date}" +%s) ))
        if [ 0 -ge ${release_age} ]; then
            echo "Probably, release: ${published_date} and current timezone were different"
            release_age=0
        fi
        tag_name=$(echo "${latest_release}" | jq --raw-output '.tag_name')
        if [ $(( 60 * 60 * 24 * 28 )) -gt ${release_age} ]; then
            echo "Release is fresh"
            echo "TAG_NAME=" >> $GITHUB_ENV
        else
            echo "Release is rotten"
            echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
        fi

    - name: Checkout current code of default branch
      if: env.TAG_NAME
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: Samsung/CredSweeper
        ref: main
        path: main

    - name: Checkout last release code
      if: env.TAG_NAME
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: Samsung/CredSweeper
        ref: ${{ env.TAG_NAME }}
        path: ${{ env.TAG_NAME }}

    - name: Compare source code of versions
      if: env.TAG_NAME
      run: diff --recursive ${{ env.TAG_NAME }}/credsweeper ${{ github.event.repository.default_branch }}/credsweeper

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
